// This file is auto-generated by Klaro Geo plugin
// It will be overwritten when you save template settings in WordPress admin
// or when a page loads and the config needs to be regenerated

var klaroConfig = {};
